apiVersion: apps/v1
kind: Deployment
metadata:
  name: titans-frontend
  namespace: titans
spec:
  replicas: 2
  selector:
    matchLabels:
      app: titans-frontend
  template:
    metadata:
      labels:
        app: titans-frontend
    spec:
      containers:
        - name: frontend
          image: REPLACE_WITH_FRONTEND_IMAGE
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: titans-frontend
  namespace: titans
spec:
  selector:
    app: titans-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
